import { useLayoutEffect } from "react"

const PrivacyPolicy = () => {
  useLayoutEffect(() => {
    window.scrollTo(0, 0)
  })
  
  return (
    <>
      <p className="privacy-policy-p">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur a erat nam at lectus urna duis. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. Consequat ac felis donec et odio pellentesque diam volutpat. Blandit massa enim nec dui nunc. Egestas congue quisque egestas diam in arcu. Diam donec adipiscing tristique risus nec feugiat in fermentum. Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Bibendum neque egestas congue quisque. Viverra vitae congue eu consequat ac felis donec. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Aliquam ut porttitor leo a diam. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Sed lectus vestibulum mattis ullamcorper velit. Aliquet nibh praesent tristique magna sit amet purus gravida quis. A scelerisque purus semper eget duis at tellus at. Mi tempus imperdiet nulla malesuada. Amet nulla facilisi morbi tempus. Integer vitae justo eget magna.</p>
      <p className="privacy-policy-p">Feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam. Augue interdum velit euismod in pellentesque massa placerat. Quisque egestas diam in arcu cursus euismod quis viverra nibh. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Eu mi bibendum neque egestas congue quisque egestas. Enim ut tellus elementum sagittis. Pretium fusce id velit ut tortor pretium viverra. Posuere morbi leo urna molestie at elementum eu facilisis. Ligula ullamcorper malesuada proin libero nunc consequat. Cras semper auctor neque vitae tempus. Eget lorem dolor sed viverra ipsum nunc. In fermentum posuere urna nec tincidunt praesent semper. Eget nunc lobortis mattis aliquam faucibus purus. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Integer eget aliquet nibh praesent tristique magna. Leo vel orci porta non pulvinar neque laoreet. Ut tellus elementum sagittis vitae et leo. Aliquam sem fringilla ut morbi tincidunt augue interdum.</p>
      <p className="privacy-policy-p">Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Nulla aliquet porttitor lacus luctus accumsan tortor posuere. Libero nunc consequat interdum varius sit amet mattis vulputate. Quis blandit turpis cursus in. A lacus vestibulum sed arcu non odio euismod lacinia. Feugiat nibh sed pulvinar proin. Tincidunt arcu non sodales neque. Eu facilisis sed odio morbi quis. Nunc sed velit dignissim sodales ut eu sem integer. Pulvinar proin gravida hendrerit lectus. In ornare quam viverra orci sagittis. Velit ut tortor pretium viverra suspendisse potenti nullam. Odio euismod lacinia at quis risus sed vulputate. Vitae tempus quam pellentesque nec nam aliquam sem. Quam vulputate dignissim suspendisse in est ante. Tellus integer feugiat scelerisque varius. A diam sollicitudin tempor id eu nisl nunc. Ridiculus mus mauris vitae ultricies leo integer.</p>
    </>
  )
}

export default PrivacyPolicy